apiVersion: apps/v1
kind: Deployment
metadata:
  name: exemple-rust
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exemple-rust
  template:
    metadata:
      labels:
        app: exemple-rust
    spec:
      containers:
      - name: exemple-rust
        image: exemple-rust
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
